/**
 * Comprehensive list of countries with flag emojis and dial codes.
 * Used in the country picker for nationality selection.
 */

export interface Country {
  name: string;
  /** Unicode flag emoji (two regional indicator letters) */
  flag: string;
  /** ISO 3166-1 alpha-2 code */
  code: string;
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", flag: "🇦🇫", code: "AF" },
  { name: "Afrique du Sud", flag: "🇿🇦", code: "ZA" },
  { name: "Albanie", flag: "🇦🇱", code: "AL" },
  { name: "Algérie", flag: "🇩🇿", code: "DZ" },
  { name: "Allemagne", flag: "🇩🇪", code: "DE" },
  { name: "Andorre", flag: "🇦🇩", code: "AD" },
  { name: "Angola", flag: "🇦🇴", code: "AO" },
  { name: "Arabie Saoudite", flag: "🇸🇦", code: "SA" },
  { name: "Argentine", flag: "🇦🇷", code: "AR" },
  { name: "Arménie", flag: "🇦🇲", code: "AM" },
  { name: "Australie", flag: "🇦🇺", code: "AU" },
  { name: "Autriche", flag: "🇦🇹", code: "AT" },
  { name: "Azerbaïdjan", flag: "🇦🇿", code: "AZ" },
  { name: "Bahreïn", flag: "🇧🇭", code: "BH" },
  { name: "Bangladesh", flag: "🇧🇩", code: "BD" },
  { name: "Belgique", flag: "🇧🇪", code: "BE" },
  { name: "Bénin", flag: "🇧🇯", code: "BJ" },
  { name: "Biélorussie", flag: "🇧🇾", code: "BY" },
  { name: "Bolivie", flag: "🇧🇴", code: "BO" },
  { name: "Bosnie-Herzégovine", flag: "🇧🇦", code: "BA" },
  { name: "Botswana", flag: "🇧🇼", code: "BW" },
  { name: "Brésil", flag: "🇧🇷", code: "BR" },
  { name: "Brunei", flag: "🇧🇳", code: "BN" },
  { name: "Bulgarie", flag: "🇧🇬", code: "BG" },
  { name: "Burkina Faso", flag: "🇧🇫", code: "BF" },
  { name: "Burundi", flag: "🇧🇮", code: "BI" },
  { name: "Cambodge", flag: "🇰🇭", code: "KH" },
  { name: "Cameroun", flag: "🇨🇲", code: "CM" },
  { name: "Canada", flag: "🇨🇦", code: "CA" },
  { name: "Cap-Vert", flag: "🇨🇻", code: "CV" },
  { name: "Chili", flag: "🇨🇱", code: "CL" },
  { name: "Chine", flag: "🇨🇳", code: "CN" },
  { name: "Chypre", flag: "🇨🇾", code: "CY" },
  { name: "Colombie", flag: "🇨🇴", code: "CO" },
  { name: "Comores", flag: "🇰🇲", code: "KM" },
  { name: "Congo (Brazzaville)", flag: "🇨🇬", code: "CG" },
  { name: "Congo (Kinshasa)", flag: "🇨🇩", code: "CD" },
  { name: "Corée du Nord", flag: "🇰🇵", code: "KP" },
  { name: "Corée du Sud", flag: "🇰🇷", code: "KR" },
  { name: "Costa Rica", flag: "🇨🇷", code: "CR" },
  { name: "Côte d'Ivoire", flag: "🇨🇮", code: "CI" },
  { name: "Croatie", flag: "🇭🇷", code: "HR" },
  { name: "Cuba", flag: "🇨🇺", code: "CU" },
  { name: "Danemark", flag: "🇩🇰", code: "DK" },
  { name: "Djibouti", flag: "🇩🇯", code: "DJ" },
  { name: "Égypte", flag: "🇪🇬", code: "EG" },
  { name: "Émirats Arabes Unis", flag: "🇦🇪", code: "AE" },
  { name: "Équateur", flag: "🇪🇨", code: "EC" },
  { name: "Érythrée", flag: "🇪🇷", code: "ER" },
  { name: "Espagne", flag: "🇪🇸", code: "ES" },
  { name: "Estonie", flag: "🇪🇪", code: "EE" },
  { name: "Éthiopie", flag: "🇪🇹", code: "ET" },
  { name: "Fidji", flag: "🇫🇯", code: "FJ" },
  { name: "Finlande", flag: "🇫🇮", code: "FI" },
  { name: "France", flag: "🇫🇷", code: "FR" },
  { name: "Gabon", flag: "🇬🇦", code: "GA" },
  { name: "Gambie", flag: "🇬🇲", code: "GM" },
  { name: "Géorgie", flag: "🇬🇪", code: "GE" },
  { name: "Ghana", flag: "🇬🇭", code: "GH" },
  { name: "Grèce", flag: "🇬🇷", code: "GR" },
  { name: "Guatemala", flag: "🇬🇹", code: "GT" },
  { name: "Guinée", flag: "🇬🇳", code: "GN" },
  { name: "Guinée-Bissau", flag: "🇬🇼", code: "GW" },
  { name: "Guinée équatoriale", flag: "🇬🇶", code: "GQ" },
  { name: "Haïti", flag: "🇭🇹", code: "HT" },
  { name: "Honduras", flag: "🇭🇳", code: "HN" },
  { name: "Hongrie", flag: "🇭🇺", code: "HU" },
  { name: "Inde", flag: "🇮🇳", code: "IN" },
  { name: "Indonésie", flag: "🇮🇩", code: "ID" },
  { name: "Irak", flag: "🇮🇶", code: "IQ" },
  { name: "Iran", flag: "🇮🇷", code: "IR" },
  { name: "Irlande", flag: "🇮🇪", code: "IE" },
  { name: "Islande", flag: "🇮🇸", code: "IS" },
  { name: "Israël", flag: "🇮🇱", code: "IL" },
  { name: "Italie", flag: "🇮🇹", code: "IT" },
  { name: "Jamaïque", flag: "🇯🇲", code: "JM" },
  { name: "Japon", flag: "🇯🇵", code: "JP" },
  { name: "Jordanie", flag: "🇯🇴", code: "JO" },
  { name: "Kazakhstan", flag: "🇰🇿", code: "KZ" },
  { name: "Kenya", flag: "🇰🇪", code: "KE" },
  { name: "Kosovo", flag: "🇽🇰", code: "XK" },
  { name: "Koweït", flag: "🇰🇼", code: "KW" },
  { name: "Laos", flag: "🇱🇦", code: "LA" },
  { name: "Liban", flag: "🇱🇧", code: "LB" },
  { name: "Libéria", flag: "🇱🇷", code: "LR" },
  { name: "Libye", flag: "🇱🇾", code: "LY" },
  { name: "Liechtenstein", flag: "🇱🇮", code: "LI" },
  { name: "Lituanie", flag: "🇱🇹", code: "LT" },
  { name: "Luxembourg", flag: "🇱🇺", code: "LU" },
  { name: "Macédoine du Nord", flag: "🇲🇰", code: "MK" },
  { name: "Madagascar", flag: "🇲🇬", code: "MG" },
  { name: "Malaisie", flag: "🇲🇾", code: "MY" },
  { name: "Mali", flag: "🇲🇱", code: "ML" },
  { name: "Malte", flag: "🇲🇹", code: "MT" },
  { name: "Maroc", flag: "🇲🇦", code: "MA" },
  { name: "Mauritanie", flag: "🇲🇷", code: "MR" },
  { name: "Mexique", flag: "🇲🇽", code: "MX" },
  { name: "Moldavie", flag: "🇲🇩", code: "MD" },
  { name: "Monaco", flag: "🇲🇨", code: "MC" },
  { name: "Mongolie", flag: "🇲🇳", code: "MN" },
  { name: "Monténégro", flag: "🇲🇪", code: "ME" },
  { name: "Mozambique", flag: "🇲🇿", code: "MZ" },
  { name: "Myanmar (Birmanie)", flag: "🇲🇲", code: "MM" },
  { name: "Namibie", flag: "🇳🇦", code: "NA" },
  { name: "Népal", flag: "🇳🇵", code: "NP" },
  { name: "Nicaragua", flag: "🇳🇮", code: "NI" },
  { name: "Niger", flag: "🇳🇪", code: "NE" },
  { name: "Nigéria", flag: "🇳🇬", code: "NG" },
  { name: "Norvège", flag: "🇳🇴", code: "NO" },
  { name: "Nouvelle-Zélande", flag: "🇳🇿", code: "NZ" },
  { name: "Oman", flag: "🇴🇲", code: "OM" },
  { name: "Ouganda", flag: "🇺🇬", code: "UG" },
  { name: "Ouzbékistan", flag: "🇺🇿", code: "UZ" },
  { name: "Pakistan", flag: "🇵🇰", code: "PK" },
  { name: "Palestine", flag: "🇵🇸", code: "PS" },
  { name: "Panama", flag: "🇵🇦", code: "PA" },
  { name: "Paraguay", flag: "🇵🇾", code: "PY" },
  { name: "Pays-Bas", flag: "🇳🇱", code: "NL" },
  { name: "Pérou", flag: "🇵🇪", code: "PE" },
  { name: "Philippines", flag: "🇵🇭", code: "PH" },
  { name: "Pologne", flag: "🇵🇱", code: "PL" },
  { name: "Portugal", flag: "🇵🇹", code: "PT" },
  { name: "Qatar", flag: "🇶🇦", code: "QA" },
  { name: "République centrafricaine", flag: "🇨🇫", code: "CF" },
  { name: "République dominicaine", flag: "🇩🇴", code: "DO" },
  { name: "République tchèque", flag: "🇨🇿", code: "CZ" },
  { name: "Roumanie", flag: "🇷🇴", code: "RO" },
  { name: "Royaume-Uni", flag: "🇬🇧", code: "GB" },
  { name: "Russie", flag: "🇷🇺", code: "RU" },
  { name: "Rwanda", flag: "🇷🇼", code: "RW" },
  { name: "Salvador", flag: "🇸🇻", code: "SV" },
  { name: "Sénégal", flag: "🇸🇳", code: "SN" },
  { name: "Serbie", flag: "🇷🇸", code: "RS" },
  { name: "Sierra Leone", flag: "🇸🇱", code: "SL" },
  { name: "Singapour", flag: "🇸🇬", code: "SG" },
  { name: "Slovaquie", flag: "🇸🇰", code: "SK" },
  { name: "Slovénie", flag: "🇸🇮", code: "SI" },
  { name: "Somalie", flag: "🇸🇴", code: "SO" },
  { name: "Soudan", flag: "🇸🇩", code: "SD" },
  { name: "Sri Lanka", flag: "🇱🇰", code: "LK" },
  { name: "Suède", flag: "🇸🇪", code: "SE" },
  { name: "Suisse", flag: "🇨🇭", code: "CH" },
  { name: "Syrie", flag: "🇸🇾", code: "SY" },
  { name: "Tanzanie", flag: "🇹🇿", code: "TZ" },
  { name: "Tchad", flag: "🇹🇩", code: "TD" },
  { name: "Thaïlande", flag: "🇹🇭", code: "TH" },
  { name: "Togo", flag: "🇹🇬", code: "TG" },
  { name: "Tunisie", flag: "🇹🇳", code: "TN" },
  { name: "Turkménistan", flag: "🇹🇲", code: "TM" },
  { name: "Turquie", flag: "🇹🇷", code: "TR" },
  { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  { name: "Uruguay", flag: "🇺🇾", code: "UY" },
  { name: "Venezuela", flag: "🇻🇪", code: "VE" },
  { name: "Vietnam", flag: "🇻🇳", code: "VN" },
  { name: "Yémen", flag: "🇾🇪", code: "YE" },
  { name: "Zambie", flag: "🇿🇲", code: "ZM" },
  { name: "Zimbabwe", flag: "🇿🇼", code: "ZW" },
  // USA last to keep French order
  { name: "États-Unis", flag: "🇺🇸", code: "US" },
];

/** Returns the flag emoji for a country name (French), or "🏳" if not found. */
export function getFlagForCountry(name: string): string {
  const found = COUNTRIES.find(
    (c) => c.name.toLowerCase() === name.toLowerCase()
  );
  return found?.flag ?? "🏳";
}
